# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
dist: xenial
latex: false
install:
- mkdir -p ~/.R
- ./util/travis/install-$TRAVIS_OS_NAME
before_script:
- export _R_CHECK_FORCE_SUGGESTS_=0
