# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
dist: xenial
latex: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8

env:
  global:
    - MAKEFLAGS="-j 2"

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = g++-8 -fPIC -flto=2" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

install:
- ./tools/travis/install-$TRAVIS_OS_NAME

before_script:
- export _R_CHECK_FORCE_SUGGESTS_=0
- echo "pkgbuild::compile_dll(); devtools::document(roclets = c('rd', 'collate', 'namespace'))" | R --vanilla

script: 
  - |
    R CMD build --no-build-vignettes .
    travis_wait 59 R CMD check --ignore-vignettes pcFactorStan*tar.gz

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL
  - travis_wait 40 Rscript -e 'covr::codecov()'

after_failure:
  - cat pcFactorStan.Rcheck/00*
