#!/bin/bash

set -ve

sudo apt-get install -yq --allow-unauthenticated --no-install-suggests --no-install-recommends \
     r-cran-rstan r-cran-testthat r-cran-mvtnorm r-cran-knitr r-cran-reshape2 r-cran-roxygen2 \
     r-cran-devtools r-cran-igraph
