#!/bin/sh

set -o errexit
set -o nounset
set -o noclobber

if [ ! -e ./tools/build ]; then
  echo "$0 must be run from the top of the project tree"
  exit
fi

git log --oneline -1
[ -d staging ] && rm -r ./staging
mkdir staging
git archive --format=tar HEAD | (cd staging; tar -xf -)
cd staging

export NOT_CRAN=true
export MAKEFLAGS=-j2

echo "pkgbuild::compile_dll(); devtools::document(roclets = c('rd', 'collate', 'namespace'))" | R --vanilla

R CMD build .
#R CMD build --no-build-vignettes .
